### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by manhluat93**

### CODE REVIEW

**Comment by zachriggle** [comment]
This should be part of your other pull request.  I'd recommend going through the steps at https://try.github.io to find out how to use Git to fork a repo, create a branch, submit a pull request, and modify the pull request in-progress.

**Comment by zachriggle** [comment]
Please consolidate this with your other pull requests, and delete this branch.

**Comment by zachriggle** [comment]
We've been informed that pwnable.kr does not want solutions for their challenges posted online.  Please delete the commits from your branch with the following commands:

```
$ git clone https://github.com/manhluat93/pwntools-write-ups
$ cd pwntools-write-ups
$ git remote add upstream https://github.com/Gallopsled/pwntools-write-ups
$ git fetch --all
$ git checkout -t origin/patch-3
$ git reset --hard upstream/master
$ git push --force origin patch-3
```

**Comment by Idolf** [comment]
Closing by request of @zachriggle.

**Pull request closed without merging**
